name: GitHub Pages

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.5.0
      with:
        node-version: ${{matrix.node-version}}
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules # 👈 path for node_modules folder
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Dependencies
      if:
        github.event.pull_request.merged==true 
      run: npm install
    - name: Build
      if: github.event.pull_request.merged==true 
      run: npm run build:prod
    #- run: npm run build --if-present

